### ISSUE TITLE
commit con método POST

### ISSUE THREAD

**Issue by antoniovalenzuela** [TransbankDevelopers/transbank-sdk-nodejs-webpay-rest-example#15]
Actualmente utilizo un SDK nodeJS example anterior (1 año aprox.) donde el "commit" funciona con el método POST.

El SDK actual tiene diversas modificaciones e intenté usar el "commit" con "POST", pero siempre retorna con "GET".

/controllers/webpay_plus.js
//cambio de 'GET' a 'POST'
let params = request.method === 'POST' ? request.query : request.body;         

/routes/webpay_plus.js
//router.get("/commit", webpayPlusController.commit); (comentado)
router.post("/commit", webpayPlusController.commit);

Consola
transbank-sdk-nodejs-webpay-rest-example:server Listening on port 3003 +0ms
POST /create 200 1389.415 ms - 4495
**GET /commit**?token_ws=01ab6c55cbc41c3e3c3536fe39844ac68161a36af636c32e8f5614c42e39fd92 404 30.412 ms - 2878

Error "NotFoundError"

Busqué en otros JS algún ajuste que tenga forzado el "GET", pero no encontré hallazgos. 

Agradezco revisar.

**Comment by ffiebig** [comment]
Hola, lamentablemente eso lo maneja directamente la API, el SDK no tiene inflección sobre como se devuelve la redirección. 

Transbank cambió el método de redirección retroactivamente.

**Comment by antoniovalenzuela** [comment]
Hola,

Igual me parece extraño porque uso un SDK anterior y el commit retorna con POST.

**Comment by mvarlic** [comment]
Se agrega soporte para GET y POST en los retornos
