### ISSUE TITLE
Error al cancelar transacción presionando "Anular compra y volver al comercio" (code 422)

### ISSUE THREAD

**Issue by irevors** [TransbankDevelopers/transbank-sdk-nodejs-webpay-rest-example#6]
Todas las operaciones parecen funcionar, salvo al intentar cancelar para regresar a la tienda. 

### Error recibido
TransbankError: Error: Request failed with status code 422
Invalid value for parameter: token

### Para reproducir
1. Comenzar cualquier proceso de pago
2.  Antes de seleccionar medio de pago, dar click en "Anular compra y volver al comercio"

### Problema aparente
Al parecer, al presionar regresar se redirecciona a la web de redirección ingresada e intenta realizar un commit según flujo de venta normal.

### Entorno:
Nodejs v12.19.0
Transbank-sdk v2.1.3

Gracias de antemano!

**Comment by antoniovalenzuela** [comment]
> Todas las operaciones parecen funcionar, salvo al intentar cancelar para regresar a la tienda.
> 
> ### Error recibido
> TransbankError: Error: Request failed with status code 422
> Invalid value for parameter: token
> 
> ### Para reproducir
> 1. Comenzar cualquier proceso de pago
> 2. Antes de seleccionar medio de pago, dar click en "Anular compra y volver al comercio"
> 
> ### Problema aparente
> Al parecer, al presionar regresar se redirecciona a la web de redirección ingresada e intenta realizar un commit según flujo de venta normal.
> 
> ### Entorno:
> Nodejs v12.19.0
> Transbank-sdk v2.1.3
> 
> Gracias de antemano!

Hola
También tengo ese problema. 

Al final no existe transacción, por tanto, creé una condición después de "let token". Primero obtengo la orden  "TBK_ORDEN_COMPRA" enviado (de retorno) en el body. 

Va más código, según lo que necesites hacer con esa orden anulada, o incluso redireccionar.


exports.commit = asyncHandler(async function (request, response, next) {
	
let token = request.body.token_ws;
		
**if (!token) {**

**var orden = request.body.TBK_ORDEN_COMPRA**
.
.
.
**response.redirect('https://URL')**

**Comment by irevors** [comment]
> Hola
> También tengo ese problema.
> 
> Al final no existe transacción, por tanto, creé una condición después de "let token". Primero obtengo la orden "TBK_ORDEN_COMPRA" enviado (de retorno) en el body.
> 
> Va más código, según lo que necesites hacer con esa orden anulada, o incluso redireccionar.
> 
> exports.commit = asyncHandler(async function (request, response, next) {
> 
> let token = request.body.token_ws;
> 
> **if (!token) {**
> 
> **var orden = request.body.TBK_ORDEN_COMPRA**
> .
> .
> .
> **response.redirect('https://URL')**



Hola @antoniovalenzuela!  

Finalmente implementé una solución similar... me tomó un tiempo entender bien el proceso al migrar desde SOAP.
Gracias por la ayuda!!
