### ISSUE TITLE
Issue at Commit: TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by jpliraa** [TransbankDevelopers/transbank-sdk-nodejs-webpay-rest-example#8]
![Captura](https://user-images.githubusercontent.com/49821117/126245532-0b67c5eb-5922-45d3-a402-b8938534daeb.PNG)

Have troubles with the node example when its commits, last week work perfectly.

TypeError: Cannot read property 'data' of undefined
    at C:\Users\jota\Desktop\APPS\NodeJS\tbk\node_modules\transbank-sdk\dist\es5\transbank\common\request_service.js:75:73    
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\jota\Desktop\APPS\NodeJS\tbk\controllers\webpay_plus.js:41:26

POST /webpay_plus/commit 404 10090.099 ms - 2832

**Comment by ffiebig** [comment]
There was a change in the API that changed the redirection from POST to GET and the example wasn't prepared for that.
