### ISSUE TITLE
Error [TransbankError]: Error: Request failed with status code 401 Not Authorized

### ISSUE THREAD

**Issue by crmsaavedra** [TransbankDevelopers/transbank-sdk-nodejs-webpay-rest-example#9]
Buenas, estaba compilando el proyecto y resulta que tengo el mismo problema en otro repositorio que tengo... estaba ocupando WebPay Plus Mall para testear y me aparece esto:
![image](https://user-images.githubusercontent.com/60436754/128288756-924543f5-e828-4606-9eda-d04b75291395.png)
![image](https://user-images.githubusercontent.com/60436754/128288793-e13775f5-55f4-4066-945a-1e0051eab1f0.png)

Cual podría ser la solución a este problema? 
Gracias

**Comment by gdespirito** [comment]
Hola! al parecer el ambiente de integración tenía problemas en la noche. No tenía nada ue ver con el proyecto de ejemplo en si!
